name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'maintenance'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'Tests'
    labels:
      - 'test'
  - title: 'Documentation'
    labels:
      - 'docs'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes'

template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
