name: 'Setup'
description: 'Setup Node.js, Corepack and install dependencies'

runs:
  using: 'composite'

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Enable Corepack for package manager support
      run: corepack enable

    - name: Install project dependencies using pnpm
      run: pnpm install
