runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - run: corepack enable
      shell: bash

    - run: pnpm install
      shell: bash
