name: setup-nodejs
description: Setup Node.js version

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '18'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Enable corepack
      shell: bash
      run: corepack enable
