name: Check Changeset

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Verify changeset exists
        run: |
          if [ -z "$(git diff --name-only origin/main...HEAD | grep '.changeset')" ]; then
            echo "No changeset found! Please add one."
            exit 1
          fi
