name: Check Changeset

on:
  workflow_call:

jobs:
  check-changeset:
    name: Check Changeset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/setup

      - name: Fetch origin main branch
        run: git fetch origin main

      - name: Commit version and changelog updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No version bump needed"
          else
            git commit -m "chore(release): bump version and update changelog"
          fi


          echo "Changeset file(s) found:"
          echo "$CHG_FILES"
