name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  lint:
    name: Lint Codebase
    needs: setup
    uses: ./.github/workflows/lint.yml

  type-check:
    name: Type Checking
    needs: lint
    uses: ./.github/workflows/type-check.yml

  codeql:
    name: CodeQL Analysis
    needs: type-check
    uses: ./.github/workflows/codeql.yml

  build:
    name: Build Project
    needs: codeql
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy Application
    needs: build
    uses: ./.github/workflows/deploy.yml
