name: CI Pipeline

on:
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    name: Lint Codebase
    uses: ./.github/workflows/lint.yml

  type-check:
    name: Type Checking
    needs: lint
    uses: ./.github/workflows/type-check.yml

  build:
    name: Build Project
    needs: type-check
    uses: ./.github/workflows/build.yml

  check-changeset:
    name: Check Changeset
    needs: build
    uses: ./.github/workflows/check-changeset.yml
