name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  type-check:
    needs: lint
    uses: ./.github/workflows/type-check.yml

  build:
    needs: type-check
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
