name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  lint:
    name: Lint Codebase
    needs: setup
    uses: ./.github/workflows/lint.yml

  type-check:
    name: Type Checking
    needs: lint
    uses: ./.github/workflows/type-check.yml

  build:
    name: Build Project
    needs: type-check
    uses: ./.github/workflows/build.yml

  check-changeset:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - name: Verify changeset exists
        run: |
          if [ -z "$(git diff --name-only origin/main...HEAD | grep '.changeset')" ]; then
            echo "No changeset found! Please add one."
            exit 1
          fi
