name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  lint:
    name: Lint Codebase
    needs: setup
    uses: ./.github/workflows/lint.yml

  type-check:
    name: Type Checking
    needs: lint
    uses: ./.github/workflows/type-check.yml

  build:
    name: Build Project
    needs: type-check
    uses: ./.github/workflows/build.yml

  version:
    name: Version Bump & Changelog Update
    needs: build
    uses: ./.github/workflows/version.yml

  changelog:
    name: Generate Changelog / Release Notes
    needs: version
    uses: ./.github/workflows/changelog.yml
