name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Create Release Pull Request
        uses: changesets/action@main
        with:
          commit: 'chore(release): version packages.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
