name: Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - run: pnpm install

      - name: Run changeset version
        run: pnpm run changeset:version

      - name: Commit version and changelog updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          git diff --cached || true
          git diff --quiet && echo "No version bump needed" || git commit -m "chore(release): bump version and update changelog"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
